server:
  port: 6688 #服务端口

spring:
  application:
    name: itcasst-microservice-config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/lxao/config.git
          username: lxao
          password: LIUXIAO@xh607
